redpanda:
  data_directory: /var/lib/redpanda/data
  empty_seed_starts_cluster: false
  seed_servers: []
  rpc_server:
    address: 0.0.0.0
    port: 33145
  kafka_api:
    - address: 0.0.0.0
      port: 9092
      authentication_method: none
  admin:
    - address: 0.0.0.0
      port: 9644
  developer_mode: true

rpk:
  enable_usage_stats: false
  tune_network: false
  tune_disk_scheduler: false
  tune_disk_nomerges: false
  tune_disk_write_cache: false
  tune_cpu: false
  tune_aio_events: false
  tune_clocksource: false
  tune_swappiness: false
  tune_transparent_hugepages: false
  enable_memory_locking: false
  tune_fstrim: false
  tune_coredump: false
  coredump_dir: /var/lib/redpanda/coredump

pandaproxy:
  pandaproxy_api:
    - address: 0.0.0.0
      port: 8082

schema_registry:
  schema_registry_api:
    - address: 0.0.0.0
      port: 8081